language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.1.302
solution: Websocket-sharp_client.sln
jobs:
  include:
  - stage: Build
    name: Build solution file
    script: dotnet build
  - stage: Tests
    name: Run End-to-End tests
    script: dotnet test test/NetCoreClientTest
  - stage: Package
    name: Create debuggable Nuget package
    script: dotnet pack --include-source src/websocket-sharp_client.csproj --output
      ../build
  - stage: Release
    name: Upload Nuget packages to github
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: UjpHWynPTRnSwaC3E4k8lR11uAC/ZVT/8J5PFO/eh6dADhdWTsJiSDjiBozCD4mCfqcRedCu8IMJQ96VvO7LyxzunWZVVCf+iLIMARZaZ0R0FKMMYZvKEHqIQnT2/i6YlkE8rf1ONDWZ8YvwtOzmAm3Ux4x++az8Eiu/5cgqZ50UCAUkB5Y/zaRIVK9jnzH/+r8y+4KNUdutai0ymJRQtnN5Dvm4VZKQbnaOIOFMNq0tslsfBx7hCvG+QOgxmBCI/rg8G8mfhpzSs4Nw2rMaGwsUZeTZlVitK7myLt7x5fF0uOKjDHoRBSudELvkAfwpCHwkg8r3Bph0pt+l/bRLbf88bpCBuxJa+jX4xNZHN90JfGc44nFBtg4iq4tY0HlMosNi89jaVxu/LXq4AuEHT6d1ozI62FsfcUZYrYjGAkBCKUcVZHB2r4Wxi/uv1m2XpjTEAbaQ094Fe8b3gYKOt0D8+ZgcfkAsFieCJsML+rWgjRVFH5b95j8BVMGkFkV0Po4PDoGCzqboCGEuquaa7auhGuvdH4FY/0LFqDtvKVdcIAeM1xFhWw86wGWJnZf25S0peLW5B1L428NiVJXDApqeEWKDae82vj427GFhhYtPt5lCRwKtEXIu3SEeWQ5QsL2mTGN8sJme5h8I8WM02+LzTN6DRtP27SRwd7I84rY=
      file: build/*.nupkg
      on:
        repo: windperson/websocket-sharp_client
      skip_cleanup: true
