language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.1.302
solution: Websocket-sharp_client.sln
jobs:
  include:
    - stage: "Build"
      script: dotnet build
    - stage: "Run Test"
      script: dotnet test test/NetCoreClientTest