language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.1.302
solution: Websocket-sharp_client.sln
jobs:
  include:
    - stage: "Build"
      name: "Build solution file"
      script: dotnet build
    - stage: "Tests"
      name: "Run End-to-End tests"
      script: dotnet test test/NetCoreClientTest
    - stage: "Package"
      name: "Create debuggable Nuget package"
      script: dotnet pack --include-source src/websocket-sharp_client.csproj --output ../build